import type { Metadata } from 'next';
import '@/styles/globals.css';
import Provider from '@/utils/Provider';
import Nav from '@/components/Common/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
